pipeline:
  build:
    image: node:latest
    commands:
      - export GRAPHQL_URL=https://data.staging.bonde.org/graphql
      - yarn
      - yarn lint
      - yarn test
    when:
      event: [push, tag]

  publish-staging:
    image: plugins/docker
    repo: nossas/bonde-bot
    secrets: [ docker_username, docker_password ]
    username: lpirola
    password: ${DOCKER_PASSWORD}
    tags:
      - ${DRONE_BRANCH}
    when:
      status: success
      branch: [hotfix-*, release-*, feature-*, develop]

  deploy-rancher-staging:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: staging/bot
    docker_image: nossas/bonde-bot:${DRONE_BRANCH}
    timeout: 360
    confirm: true
    secrets: [ rancher_access_key, rancher_secret_key ]
    when:
      status: success
      branch: [hotfix-*, release-*, feature-*, develop]

  publish-production:
    image: plugins/docker
    repo: nossas/bonde-bot
    secrets: [ docker_username, docker_password ]
    username: lpirola
    password: ${DOCKER_PASSWORD}
    tags:
      - ${DRONE_TAG##v}
    when:
      status: success
      event: tag

  deploy-rancher-production:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: bonde/bot
    docker_image: "nossas/bonde-bot:${DRONE_TAG##v}"
    timeout: 360
    confirm: true
    secrets: [ rancher_access_key, rancher_secret_key ]
    when:
      status: success
      event: tag

  notify:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: bonde_bots
    username: CI - ${DRONE_REPO_NAME}
    when:
      event: [ push, tag, build, publish, deployment, pull_request ]
      status: [ success, failure ]

services:
  database:
    image: postgres:9.6
    # commands:
      # - psql -c 'create database bonde; create schema postgraphql;' -hpostgres -Upostgres

  data:
    image: nossas/bonde-graphql
    commands:
      - export SCHEMA_NAME=postgraphql
      - export DATABASE_URL=postgres://postgres@database/postgres
      - export JWT_SECRET=create_new_token
      - export JWT_TYPE=postgraphql.jwt_token
      - export PG_DEFAULT_ROLE=postgres
