pipeline:
  build:
    image: node:latest
    commands:
      - yarn
    when:
      event: [push, tag]

  publish-staging:
    image: plugins/docker
    repo: nossas/bonde-bot
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_BRANCH}
    when:
      status: success
      branch: [hotfix-*, release-*, feature-*, develop]

  deploy-staging:
    image: appleboy/drone-ssh
    host: staging.bonde.org
    username: ubuntu
    command_timeout: 120
    port: 22
    secrets: [ ssh_key ]
    script:
      - sudo docker pull nossas/bonde-bot:${DRONE_BRANCH}
      - sudo docker tag nossas/bonde-bot:${DRONE_BRANCH} dokku/beta:latest
      - dokku tags:deploy beta latest
    when:
      status: success
      branch: [hotfix-*, release-*, feature-*, develop]

  publish-production:
    image: plugins/docker
    repo: nossas/bonde-bot
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_TAG##v}
    when:
      status: success
      event: tag

  deploy-production:
    image: appleboy/drone-ssh
    host: ssh.bonde.org
    username: ubuntu
    command_timeout: 120
    port: 22
    secrets: [ ssh_key ]
    script:
      - sudo docker pull nossas/bonde-bot:${DRONE_TAG##v}
      - sudo docker tag nossas/bonde-bot:${DRONE_TAG##v} dokku/beta:latest
      - dokku tags:deploy beta latest
    when:
      status: success
      event: tag

  notify:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: n_tech
    username: CI - ${DRONE_REPO_NAME}
    when:
      event: [ push, tag, build, publish, deployment, pull_request ]
      status: [ success, failure ]
